project_id = "tahfemcxtbbixsvsurfq"

[functions.generate-notes]
verify_jwt = false

[functions.find-video]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.adaptive-question]
verify_jwt = false
